from 爆发 import compute_weighted_average
from 复合 import calculate_complete_compound_difficulty
from 节奏 import compute_final_rhythm_difficulty
from 手速 import compute_weighted_average
from 体力 import calculate_result